### ISSUE TITLE
[BUG] MDCTextField component gets out of focused while typing. And Floating label gets cut when user taps out side after typing

### ISSUE THREAD

**Issue by RotBolt** [mpetuska/kmdc#76]
As shown in the below screenshot. Floating label gets cut, after user types something
Also focus gets out when user starts typing

![Screenshot 2022-01-17 at 11 17 53 AM](https://user-images.githubusercontent.com/24780524/149714578-6a3ca199-0057-428c-93e3-0a5e3d83fb3f.png)

**Comment by RotBolt** [comment]
This is the code snippet
```
            val annualCtcState = remember { mutableStateOf("") }
            MDCTextField(
                annualCtcState.value,
                {
                    type = MDCTextFieldCommonOpts.Type.Outlined
                    label = "Annual CTC"
                },
                {
                    title("Annual CTC")
                    onInput {
                        annualCtcState.value = it.value
                    }
                }
            )
```

**Comment by rocketraman** [comment]
Seeing the same thing. It looks like the upstream MDCTextField calculates and sets a label width, so this `Span` gets rendered with a `style=width: <value>px`:

https://github.com/mpetuska/kmdc/blob/07aed3fa1465f186003ad6d6f90811e9b567740a/lib/kmdc-textfield/src/jsMain/kotlin/MDCTextField.kt#L167

There is some discussion of this issue here: https://github.com/material-components/material-components-web/issues/4328.

It looks like a call to `layout` after a value is set might fix / work around it.

**Comment by RotBolt** [comment]
No, I think this is the behavior, I also concluded this behavior

**Comment by rocketraman** [comment]
@mpetuska That's too bad. What is your general philosophy on issues like this? I see the following options:

1) Do nothing, let upstream solve it.

2) Work around the issue in kmdc.

3) Expose the necessary machinery (i.e. in this case the layout call) as API in kmdc to allow users of kmdc to work around the issue themselves.

My preference here would be option 2. Option 3 feels like a layering violation, and option 1 -- well who knows it takes them to fix it. The issue is in their backlog so they apparently don't think it very important.

**Comment by mpetuska** [comment]
Definitely #2. I'll see if i can incorporate that layout call into compose lifecycle once I get a chance to sit down with it

**Comment by mpetuska** [comment]
Or maybe just raise a PR and fix it ourselves upstream if nothing works

**Comment by rocketraman** [comment]
> Or maybe just raise a PR and fix it ourselves upstream if nothing works

True, always an option as well!

**Comment by gsteckman** [comment]
For the focus visual effect, it looks like the css class mdc-text-field--focused is applied via javascript with a focus listener. When you type a character, compose will regenerate the element, which will have the default classes that don't include mdc-text-field--focused. Therefore the focus visual is lost.

For this case then the focus state would also need to be tracked in order to set the class on recomposition.

Implementing an [Adapter ](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md) may be another approach.

**Comment by RotBolt** [comment]
Hey thanks Greg for this input. if you don't mind, I would like to create
adapter and contribute to this issue. This will be interesting challenge
for me.

**Comment by mpetuska** [comment]
I'd like to avoid custom adapters if possible. Looks like the issue here is unwanted recomposition, should be solvable via DOM side-effects and refs. @RotBolt feel free to give it a stab. Ping back here or on slack if you need help at any point :smile:

**Comment by gsteckman** [comment]
I'm seeing similar behavior with Menu. I'm trying to build an "autocomplete" widget with a combination of a textfield and menu. When typing in the textfield, the menu closes, presumably because the textfield grabs back the focus, and the menu won't show again even when open=true in the next recomposition. The menu surface element is getting the class mdc-menu-surface--open set, and then removed when the menu closes. I also tried taking out the key on the DomSideEffect that sets the open property
`DomSideEffect/*(options.open)*/ { scope ->
      scope.mdc<MDCMenuModule.MDCMenu> { open = options.open }
    }`
but without success. I'm not sure why on recomposition this is not causing the menu to open (again).

Really, the focus in/out logic should be modified here so if the focus is with the textfield, the menu remains open, and if the focus is with the textfield, the focus visual on the textfield remains. But if the focus leaves either component, then the menu closes and the textfield goes back to the unfocused visual state.

**Comment by RotBolt** [comment]
How does the katalog tooling solves this issue?

**Comment by mpetuska** [comment]
It solves partially. That pr is humongous and fixes lots of issues with the components tgat I've found while rewriting previews. However label cropping is still present for this component.

**Comment by mpetuska** [comment]
P.S. I've just tried that `layout()` call and sadly it did nothing. So there's not even any real workaround for this...

**Comment by mpetuska** [comment]
I think I've managed to fixed it by controlling MDC value prop. Could anyone try to reproduce the issue [here](https://mpetuska.github.io/kmdc/#MDCTextField)? (I couldn't after the changes)

Looking at you @RotBolt :laughing:

**Comment by rocketraman** [comment]
> Could anyone try to reproduce the issue [here](https://mpetuska.github.io/kmdc/#MDCTextField)?

I couldn't reproduce it.

**Comment by mpetuska** [comment]
I'll wait for @RotBolt to try it too before merging. But good news regardless!

**Comment by mpetuska** [comment]
I'm closing this for now, but if anyone encounters any of the following again please let me know here and I'll reopen the issue:
1. Focus loss when typing
2. Label cropping for outlined variant

**Comment by mpetuska** [comment]
FYI @gsteckman
Anchored MDCMenu in the [showcase](https://kmdc.petuska.dev/#MDCMenu) is very close to what you are trying to build.

**Comment by RotBolt** [comment]
I am nkt able to reproduce it
