### ISSUE TITLE
MDCMenu onSelected gets called twice

### ISSUE THREAD

**Issue by gsteckman** [mpetuska/kmdc#82]
When a menu item is selected, the onSelected callback is called twice. To reproduce, add a console.log statement in the onSelected callback of the sandbox Menu example and you'll see it get logged twice.

**Comment by mpetuska** [comment]
The issue was due to underlying MDCList spawning the same event on item selection, therefore duplicating it in addition to the events spawned by MDCMenu component. This is now fixed in the linked PR.

Note to self - make sure that child MDC components do not initialise their JS when using them to build a higher level component.
